#!/usr/bin/python3
# COMP3311 21T3 Ass2 ... print a transcript for a given student

import sys
import psycopg2
import re
from helpers import getStudent, uoc_valid, print_transcript



# define any local helper functions here

### set up some globals

usage = f"Usage: {sys.argv[0]} zID"
db = None

### process command-line args

argc = len(sys.argv)
if argc < 2:
  print(usage)
  exit(1)
zid = sys.argv[1]
if zid[0] == 'z':
  zid = zid[1:8]
digits = re.compile("^\d{7}$")
if not digits.match(zid):
  print(f"Invalid student ID {zid}")
  exit(1)

# manipulate database
cur = None 
query = "select * from transcript(%s)"
query_people = "select * from people where id = %s"
try:
  db = psycopg2.connect("dbname=mymyunsw")
  stuInfo = getStudent(db,zid)
  if not stuInfo:
    print(f"Invalid student ID {zid}")
    exit()

  cur = db.cursor()
  cur.execute(query_people,[zid])
  person = cur.fetchone()
  print(f"{person[0]} {person[1]}, {person[2]}")

  cur.execute(query,[zid])
  results = cur.fetchall()
  print_transcript(results)

  #print(stuInfo) # debug
  # Print transcript for Student
  # ... add your code here ...
  
except Exception as err:
  print("DB error: ", err)
finally:
  if db:
    db.close()


